"""
secedit_parser.py
=================
Parser for secedit config files generated by `secedit /export`.
"""

def parse_password_policy(secedit_output: str) -> dict:
    """
    Parses the raw string output of `secedit /export /cfg <path> /quiet`
    and extracts the password policy and account lockout policy fields from
    the [System Access] section.

    Usage Example:
        >>> output = \"\"\"
        ... [System Access]
        ... MinimumPasswordLength = 8
        ... PasswordComplexity = 1
        ... \"\"\"
        >>> parse_password_policy(output)
        {'MinimumPasswordAge': None, 'MaximumPasswordAge': None, 'MinimumPasswordLength': 8, 'PasswordComplexity': 1, 'PasswordHistorySize': None, 'LockoutBadCount': None, 'LockoutDuration': None, 'ResetLockoutCount': None, 'RequireLogonToChangePassword': None, 'ClearTextPassword': None}

    Args:
        secedit_output (str): The raw multiline string from secedit.

    Returns:
        dict: A flat dictionary containing the extracted keys as integers or None.
    """
    keys_to_extract = {
        "MinimumPasswordAge",
        "MaximumPasswordAge",
        "MinimumPasswordLength",
        "PasswordComplexity",
        "PasswordHistorySize",
        "LockoutBadCount",
        "LockoutDuration",
        "ResetLockoutCount",
        "RequireLogonToChangePassword",
        "ClearTextPassword"
    }

    # Initialize all target keys to None
    result = {key: None for key in keys_to_extract}

    # Case-insensitive mapping from lowercase names back to schema casing
    keys_map = {key.lower(): key for key in keys_to_extract}

    in_system_access = False

    # Split output into lines, handling \r\n and \n transparently
    for line in secedit_output.splitlines():
        line = line.strip()
        if not line:
            continue

        # Identify section headings
        if line.startswith("[") and line.endswith("]"):
            section_name = line[1:-1].strip()
            # Check if we are entering [System Access]
            if section_name.lower() == "system access":
                in_system_access = True
            else:
                in_system_access = False
            continue

        # If inside [System Access], process settings
        if in_system_access:
            if "=" in line:
                key, val = line.split("=", 1)
                key = key.strip()
                val = val.strip()

                key_lower = key.lower()
                if key_lower in keys_map:
                    schema_key = keys_map[key_lower]
                    try:
                        result[schema_key] = int(val)
                    except ValueError:
                        # Resilient to non-int values in the output
                        result[schema_key] = None

    return result


if __name__ == "__main__":
    sample_input = """
[Unicode]
Unicode=yes
[System Access]
MinimumPasswordAge = 1
MaximumPasswordAge = 42
MinimumPasswordLength = 8
PasswordComplexity = 1
PasswordHistorySize = 24
LockoutBadCount = 5
LockoutDuration = 30
ResetLockoutCount = 30
RequireLogonToChangePassword = 0
ClearTextPassword = 0
[Registry Values]
signature="$CHICAGO$"
Revision=1
"""
    import json
    parsed_config = parse_password_policy(sample_input)
    print("Parsed result:")
    print(json.dumps(parsed_config, indent=4))
